app = 'msfjarvis-rsspub'
primary_region = 'ams'

[build]
  image = 'ghcr.io/harshit181/rsspub:latest'

[env]
  RUST_LOG = 'info,html5ever=error'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'rsspub_data'
  destination = '/app/db'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
